### ISSUE TITLE
Twitter dev account needed

### ISSUE THREAD

**Issue by sario528** [sopel-irc/sopel-twitter#17]
Twitter now requires you to apply for a dev account before you can generate a new api key.

**Comment by dgw** [comment]
Correct. There's nothing we can do about it, though, so I don't understand why this issue was opened.

**Comment by dgw** [comment]
In case this was what you were going for (and it just wasn't communicated well), the README has been updated to reflect the current process of getting keys: ac359b9255903c3867db776efe22fb7c8b378f4e
