### ISSUE TITLE
Response says 'op' not 'on'

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel-twitter#18]
`12:50:20 <+ZppixBot> [ Nick🇬🇧🇪🇺 OP Twitter: "+UPDATE+ Boris Johnson requested the Queen that he use Buckingham Palace grounds “for his free time” to escape media attention and the general public." ] - twitter.com
`
should be
`12:50:20 <+ZppixBot> [ Nick🇬🇧🇪🇺 ON Twitter: "+UPDATE+ Boris Johnson requested the Queen that he use Buckingham Palace grounds “for his free time” to escape media attention and the general public." ] - twitter.com`

(In lowercase but made caps to add emphasis.)

For some reason, I can't see where the bug is so can someone look?

**Comment by dgw** [comment]
That's not this plugin's output; it's `url.py` from Sopel core (or your bot's hacked version). Twitter must be translating the page title based on your instance's IP geolocation.

**Comment by RhinosF1** [comment]
> That's not this plugin's output; it's `url.py` from Sopel core (or your bot's hacked version). Twitter must be translating the page title based on your instance's IP geolocation.

The output only changed to the above when I installed sopel-twitter but yes annoyingly we have a hacked url module.

**Comment by dgw** [comment]
Correlation ≠ causation. Output from sopel-twitter looks nothing like that:

```irc
16:52:51 <~dgw> https://twitter.com/nicktolhurst/status/1265559020787597316
16:52:52 <&Kaede> [Twitter] Nick🇬🇧🇪🇺 (@nicktolhurst): +UPDATE+ ⏎  ⏎ Boris Johnson requested the Queen that he use Buckingham Palace grounds “for his free time” to escape media attention and the general public. | 794 RTs | 1310 ♥s | Posted: Wednesday, May 27, 2020 03:22:38 (CDT)
16:52:54 <SopelPi> [ Nick🇬🇧🇪🇺 on Twitter: "+UPDATE+ Boris Johnson requested the Queen that he use Buckingham Palace grounds “for his free time” to escape media attention and the general public." ] - twitter.com
```

Note, SopelPi is running stock 7.0.4, without this plugin, so the url plugin handles the tweet link (and without this "bug", probably because its IP is American). Kaede runs sopel-twitter.

**Comment by RhinosF1** [comment]
> Correlation ≠ causation. Output from sopel-twitter looks nothing like that:
> 
> ```
> 16:52:51 <~dgw> https://twitter.com/nicktolhurst/status/1265559020787597316
> 16:52:52 <&Kaede> [Twitter] Nick🇬🇧🇪🇺 (@nicktolhurst): +UPDATE+ ⏎  ⏎ Boris Johnson requested the Queen that he use Buckingham Palace grounds “for his free time” to escape media attention and the general public. | 794 RTs | 1310 ♥s | Posted: Wednesday, May 27, 2020 03:22:38 (CDT)
> 16:52:54 <SopelPi> [ Nick🇬🇧🇪🇺 on Twitter: "+UPDATE+ Boris Johnson requested the Queen that he use Buckingham Palace grounds “for his free time” to escape media attention and the general public." ] - twitter.com
> ```
> 
> Note, SopelPi is running stock 7.0.4, without this plugin, so the url plugin handles the tweet link (and without this "bug", probably because its IP is American). Kaede runs sopel-twitter.

I also found a lot of find_lines logspam as I debugged this so I guess we’ve got a broken hack again, sorry for the mess.
