### ISSUE TITLE
Improve Errors

### ISSUE THREAD

**Issue by ghost** [sopel-irc/sopel-twitter#45]
I haven't looked at the upstream tool used, but if there's a separate error message provided for 18+ (NSFW) tweets, it would be good for Sopel to reply with that, rather than saying (very incorrectly) that the tweet is not found/deleted.

**Comment by dgw** [comment]
> if there's a separate error message provided for 18+ (NSFW) tweets

[There isn't.](https://mahrtayyab.github.io/tweety_docs/exceptions.html) The plugin would already handle it separately if there was.
