### ISSUE TITLE
Tweets from locked accounts cause uncaught exception

### ISSUE THREAD

**Issue by half-duplex** [sopel-irc/sopel-twitter#62]
Linking a tweet from a locked account (that the bot account doesn't have access to) causes an uncaught exception. This seems like an upstream tweety bug, but for now we could just catch and pass, or catch and "An error occurred... The account may be locked"?

Tested with tweety-ns 1.0.9.9 and 1.1.2, same behavior. Logs below are from 1.1.2.

```
22:21:49 <mal> https://twitter.com/[redacted]
22:21:50 <Sopel> Unexpected AttributeError ('NoneType' object has no attribute 'get') from mal. Message was: https://twitter.com/[redacted]
```

Logs:
```
sopel.bot            ERROR   : Unexpected AttributeError ('NoneType' object has no attribute 'get') from mal. Message was: https://twitter.com/[redacted]
Traceback (most recent call last):
  File "sopel/bot.py", line 695, in call_rule
    rule.execute(sopel, trigger)
  File "sopel/plugins/rules.py", line 1274, in execute
    exit_code = self._handler(bot, trigger)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/sopel_twitter/__init__.py", line 197, in url_status
    output_status(bot, trigger, trigger.group("status"))
  File "env/lib/python3.11/site-packages/sopel_twitter/__init__.py", line 226, in output_status
    tweet = app.tweet_detail(id_)
            ^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/tweety/bot.py", line 820, in tweet_detail
    tweet = Tweet(self, entry, response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 42, in new_init
    init(self, *_args, **_kwargs) # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 166, in __init__
    self._format_tweet()
  File "env/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 261, in _format_tweet
    if self._tweet.get('tweet'):
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by dgw** [comment]
Upstream author is pretty responsive to bug reports. There are [`UserProtected`](https://github.com/mahrtayyab/tweety/blob/a7e5be39b75e14b81c9093bffd647f011cb73f35/src/tweety/exceptions_.py#L93) and [`ProtectedTweet`](https://github.com/mahrtayyab/tweety/blob/a7e5be39b75e14b81c9093bffd647f011cb73f35/src/tweety/exceptions_.py#L194) exception types already so this is most likely a missed code path.

(A quick, helpful PR would be to add handling of `ProtectedTweet` exceptions, which must not have existed yet when the current error handling in this plugin was written. It handles `UserProtected`, though. 🤔)

**Comment by dgw** [comment]
`tweety-ns` 1.1.4+ (as versioned on PyPI) should have a new `is_user_authorized` attr available for this purpose. I've made the trivial code changes in d520a649d0ef784bb3c177dcd0c1bd5e26bead09 but haven't tested it thoroughly yet, nor looked at the exception piece of this.
